### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#63]
Cover the legislation explorer with tests that prove:

- The page loads and shows metadata on the loaded tax and benefit system.
- The search does filter the list.
- Navigating to an item of the list shows details.
- Going back keeps the search.

**Comment by cbenz** [comment]
@MattiSG I chose [Watai](https://github.com/MattiSG/Watai) to implement integration tests.

I have a first error with my code in the `integration-tests` branch:

```sh
~/D/o/legislation-explorer (master|✚1…) $ watai tests
error: **Error in file "/home/cbenz/Dev/openfisca/legislation-explorer/tests/1 - AppScenario.js"** path=/home/cbenz/Dev/openfisca/legislation-explorer/tests/1 - AppScenario.js
debug: /home/cbenz/Dev/openfisca/legislation-explorer/tests/1 - AppScenario.js:5
    "AppComponent.countryPackageInfo": countryPackageNameAndDescription
                                       ^
ReferenceError: countryPackageNameAndDescription is not defined
    at /home/cbenz/Dev/openfisca/legislation-explorer/tests/1 - AppScenario.js:5:40
    at Object.exports.runInContext (vm.js:44:17)
    at loadScenario (/usr/local/lib/node_modules/watai/src/controller/SuiteLoader.js:348:7)
    at wrapper.extend.$owner (/usr/local/lib/node_modules/watai/node_modules/mootools/lib/mootools-core-1.4.5-server.js:997:23)
    at Function.<anonymous> (/usr/local/lib/node_modules/watai/node_modules/mootools/lib/mootools-core-1.4.5-server.js:320:44)
    at loadAllFiles (/usr/local/lib/node_modules/watai/src/controller/SuiteLoader.js:257:10)
    at wrapper.extend.$owner (/usr/local/lib/node_modules/watai/node_modules/mootools/lib/mootools-core-1.4.5-server.js:997:23)
From previous event:
    at getRunner (/usr/local/lib/node_modules/watai/src/controller/SuiteLoader.js:175:4)
    at wrapper.extend.$owner (/usr/local/lib/node_modules/watai/node_modules/mootools/lib/mootools-core-1.4.5-server.js:997:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/watai/src/index.js:40:7)
/home/cbenz/Dev/openfisca/legislation-explorer/tests/1 - AppScenario.js:5
    "AppComponent.countryPackageInfo": countryPackageNameAndDescription
                                       ^
ReferenceError: countryPackageNameAndDescription is not defined
    at /home/cbenz/Dev/openfisca/legislation-explorer/tests/1 - AppScenario.js:5:40
    at Object.exports.runInContext (vm.js:44:17)
    at loadScenario (/usr/local/lib/node_modules/watai/src/controller/SuiteLoader.js:348:7)
    at wrapper.extend.$owner (/usr/local/lib/node_modules/watai/node_modules/mootools/lib/mootools-core-1.4.5-server.js:997:23)
    at Function.<anonymous> (/usr/local/lib/node_modules/watai/node_modules/mootools/lib/mootools-core-1.4.5-server.js:320:44)
    at loadAllFiles (/usr/local/lib/node_modules/watai/src/controller/SuiteLoader.js:257:10)
    at wrapper.extend.$owner (/usr/local/lib/node_modules/watai/node_modules/mootools/lib/mootools-core-1.4.5-server.js:997:23)
From previous event:
    at getRunner (/usr/local/lib/node_modules/watai/src/controller/SuiteLoader.js:175:4)
    at wrapper.extend.$owner (/usr/local/lib/node_modules/watai/node_modules/mootools/lib/mootools-core-1.4.5-server.js:997:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/watai/src/index.js:40:7)
```

Do you have any clue? Looking at https://github.com/MattiSG/Watai/wiki/Troubleshooting did not seem to help.

I guess I have to start `selenium` but here is my error (another one):

```sh
~ $ selenium 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/selenium-server/lib/runner/../../logs/selenium.out'
    at Error (native)
```

> I installed `npm install --global selenium-server` and `apt install openjdk-9-jre` under Debian.

**Comment by MattiSG** [comment]
This is a question for https://github.com/eugeneware/selenium-server. Maybe try to use another wrapper?

**Comment by MattiSG** [comment]
Or no wrapper and just install the JAR.

**Comment by fpagnoux** [comment]
@cbenz in `AppFixture.js`:
```js
countryPackageNameAndDescription: /.+@\d+.\d+.\d+/
```
-->
```js
`countryPackageNameAndDescription = /.+@\d+.\d+.\d+/
```

**Comment by fpagnoux** [comment]
If you want, we can pair on this tomorrow, I have some memories about setting up tests in mes-aides.

**Comment by cbenz** [comment]
Indeed! I ended up finding the reason, but I did not commit. Thanks anyway, and yes for pairing tomorrow.

**Comment by MattiSG** [comment]
> I ended up finding the reason, but I did not commit.

In order to make working in an async manner doable, please remember to always update help requests when they become outdated 🙂
